# Node.js with Vue
# Build a Node.js project that uses Vue.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript
#
# You can set Variables on pipelines web console.
# @see https://docs.microsoft.com/zh-cn/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#secret-variables
#
# Variables list:
# variables name      Required        Keep secret        Default value         Example
# GITHUB_TOKEN           yes              yes
# BUILD_SCRIPT           no               no             yarn docs:build
# CNAME                  no               no                                   www.youdomain.com
# TARGET_BRANCH          no               no             gh-pages              master
#
# GITHUB_TOKEN generate from: https://github.com/settings/tokens


# @see https://docs.microsoft.com/zh-cn/azure/devops/pipelines/repos/github?view=azure-devops&tabs=yaml#ci-triggers
trigger:
  branches:
    include:
    - '*'  # must quote since "*" is a YAML reserved character; we want a string, you can use: {master} or {your branch name}

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- task: InstallSSHKey@0
  inputs:
    knownHostsEntry: '$(HOST_ADDR)'
    sshKeySecureFile: 'deploy_rsa'

- bash: |
    echo "node version:"
    node --version
    echo "yarn version:"
    yarn --version
    scp -P $(HOST_PORT) -o StrictHostKeyChecking=no -r docs/* $(HOST_USER)@$(HOST_ADDR):/data/docker/wwwroot/test/
  displayName: 'Push to Hosts server.'