# Node.js with Vue
# Build a Node.js project that uses Vue.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript
#
# You can set Variables on pipelines web console.
# @see https://docs.microsoft.com/zh-cn/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#secret-variables
#
# Variables list:
# variables name      Required        Keep secret        Default value         Example
# GITHUB_TOKEN           yes              yes
# BUILD_SCRIPT           no               no             yarn docs:build
# CNAME                  no               no                                   www.youdomain.com
# TARGET_BRANCH          no               no             gh-pages              master
#
# GITHUB_TOKEN generate from: https://github.com/settings/tokens


# @see https://docs.microsoft.com/zh-cn/azure/devops/pipelines/repos/github?view=azure-devops&tabs=yaml#ci-triggers
trigger:
  branches:
    include:
    - '*'  # must quote since "*" is a YAML reserved character; we want a string, you can use: {master} or {your branch name}

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    # 注意设置版本号，选12.x，默认是10.x，非常坑
    versionSpec: '12.x'
    checkLatest: true
  displayName: 'Install Node.js'

- bash: |
    yarn install --no-lockfile
    mkdir -p /tmp/dist
    # For not secret variables,use $variablesname or ${variablesname}
    # For secret variables, use $(variablesname)

    if [[ -z "${BUILD_SCRIPT}" ]]; then
      script="yarn docs:build -d /tmp/dist"
    else
      script="${BUILD_SCRIPT} -d /tmp/dist"
    fi
    echo "Start building:"$script
    eval $script

    # set variable: build_dir 
    # @see https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops
    echo "##vso[task.setvariable variable=build_path]/tmp/dist"
  displayName: 'yarn install and build'

- bash: |
    if [ "$CNAME" ]; then
      echo "Generating a CNAME file..."
      echo $CNAME > CNAME
    fi
  workingDirectory: $(build_path)
  displayName: 'Generate a CNAME file'

- script: |
    # use $(Build.Repository.ID) or ${BUILD_REPOSITORY_ID}
    DEPLOY_REPO="https://$(GITHUB_TOKEN)@github.com/$(Build.Repository.ID).git"
    
    if [[ -z "$TARGET_BRANCH" ]]; then
      DEPLOY_BRANCH="gh-pages"
    else
      DEPLOY_BRANCH="$TARGET_BRANCH"
    fi

    if [[ -z "$(GITHUB_TOKEN)" ]]; then
      echo "ERROR: github token is not valid"
      exit 0
    else
      echo "github token is valid"
    fi

    git init
    git config user.name "Azure pipelines"
    git config user.email "pipelines@users.noreply.github.com"
    pwd
    ls
    git add --all;
    git commit -m"Pipelines-Bot: Auto deploy";
    git push --force $DEPLOY_REPO master:$DEPLOY_BRANCH
  workingDirectory: $(build_path)
  displayName: '[Git] Commit and push to Github Pages branch'

- task: InstallSSHKey@0
  inputs:
    # Set "HOST_ADDR" Viriables on pipelines edit web interface
    knownHostsEntry: '$(HOST_ADDR)'
    # @see https://docs.microsoft.com/en-us/azure/devops/pipelines/library/secure-files?view=azure-devops
    # upload your ssh private key on pipelines "Labrary"
    sshKeySecureFile: 'deploy_rsa'
  displayName: 'install ssh key.'

- bash: |
    # Set HOST_PORT,HOST_USER,HOST_ADDR and HOST_DEPLOY_PATH Viriables on the pipelines edit web interface
    scp -P $(HOST_PORT) -o StrictHostKeyChecking=no -r $(build_path)/* $(HOST_USER)@$(HOST_ADDR):$(HOST_DEPLOY_PATH)
  displayName: 'Push to Hosts server.'